const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('xiaov2b', {
  authStatus: () => ipcRenderer.invoke('auth:status'),
  restore: () => ipcRenderer.invoke('auth:restore'),
  login: (payload) => ipcRenderer.invoke('auth:login', payload),
  logout: () => ipcRenderer.invoke('auth:logout'),
  refresh: () => ipcRenderer.invoke('dashboard:refresh'),
  connect: () => ipcRenderer.invoke('core:connect'),
  disconnect: () => ipcRenderer.invoke('core:disconnect'),
  setMode: (mode) => ipcRenderer.invoke('core:setMode', mode),
  selectProxy: (proxyName) => ipcRenderer.invoke('core:selectProxy', proxyName),
  measureLatency: (nodes) => ipcRenderer.invoke('node:latency', nodes),
  syncMode: (mode) => ipcRenderer.invoke('mode:sync', mode),
  getTraffic: () => ipcRenderer.invoke('core:traffic'),
  localLocation: () => ipcRenderer.invoke('network:localLocation'),
  getStartup: () => ipcRenderer.invoke('settings:getStartup'),
  setStartup: (enabled) => ipcRenderer.invoke('settings:setStartup', enabled),
  createOrder: (payload) => ipcRenderer.invoke('order:create', payload),
  checkCoupon: (payload) => ipcRenderer.invoke('coupon:check', payload),
  orderDetail: (tradeNo) => ipcRenderer.invoke('order:detail', tradeNo),
  paymentMethods: () => ipcRenderer.invoke('order:paymentMethods'),
  checkoutOrder: (payload) => ipcRenderer.invoke('order:checkout', payload),
  checkOrder: (tradeNo) => ipcRenderer.invoke('order:check', tradeNo),
  cancelOrder: (tradeNo) => ipcRenderer.invoke('order:cancel', tradeNo),
  makeQrCode: (value) => ipcRenderer.invoke('qr:encode', value),
  paymentImageDataUrl: (url) => ipcRenderer.invoke('payment:imageDataUrl', url),
  openExternal: (url) => ipcRenderer.invoke('external:open', url),
  onCoreStatus: (callback) => ipcRenderer.on('core:status', (_event, status) => callback(status)),
  onCoreProgress: (callback) => ipcRenderer.on('core:progress', (_event, progress) => callback(progress)),
  onModeChanged: (callback) => ipcRenderer.on('mode:changed', (_event, result) => callback(result)),
  windowMinimize: () => ipcRenderer.invoke('window:minimize'),
  windowHideToTray: () => ipcRenderer.invoke('window:hideToTray'),
  windowMaximize: () => ipcRenderer.invoke('window:maximize')
});
